apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    #define the Pods which need to be controlled
    matchLabels:
      app: {{ .Values.metadata.name }}
  template:
    #pods label
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    #indicates that the Pods run one container
    spec:
      containers:
        - name: {{ .Values.metadata.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: 8081