apiVersion: v1
kind: Service
metadata:
  name: service-a0
spec:
  type: NodePort
  selector:
    # target pods with label
    app: service-a0
  ports:
    - protocol: TCP
      port: 8081
#      target the port of the pod
#      targetPort: 8081